# Generated by Django 4.2.11 on 2024-12-02 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0002_alter_firefighters_rank_alter_firefighters_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
